apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: diego.maciel@tallos.com.br
    privateKeySecretRef:
      name: letsencrypt
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        route53:
          region: us-east-2
          hostedZoneID: XXXXXXXXXXXXXXXXXXXXX
    - http01:
        ingress:
          class: nginx
